
[cursor]
unfocused_hollow = true

[debug]
render_timer = false

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.normal]
family = "Roboto Mono"

# [shell]
# modifiers = "Super"
# program = "/bin/zsh"
#
# [shell.launcher]
# program = "xdg-open"

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
title = "Alacritty"

[general]
import = ["/home/hayden/.config/alacritty/themes/one_dark.toml"]
