#!/bin/zsh

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':')"

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export READER="zathura"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
#export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export GOPATH="$XDG_DATA_HOME/go"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$XDG_CONFIG_HOME/gems/ruby/2.7.0/bin"
export PATH="$PATH:$XDG_CONFIG_HOME/rvm/bin"
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export PATH="$PATH:/var/lib/snapd/snap/bin"
export NVIM_DIR="$XDG_CONFIG_HOME/nvim"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
export RVM_DIR="$HOME/.rvm"
export RC_DIR="$XDG_CONFIG_HOME/rc"

# Start graphical server on tty1 if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! ps -e | grep -qw Xorg && exec startx

sh $RC_DIR/scripts/layout.sh -w
xrb $RC_DIR/Xresources &	# Uncomment to use Xresources colors/settings on startup
xset r rate 250 25 &	# Speed xrate up
unclutter &		# Remove mouse when idle
bluetoothctl power on &
setxkbmap -layout gb -option &
