#!/bin/bash

i3lock -c 222222

# i3lock -c 222222 -e &
#
# pid=$$
#
# log() {
#   echo "[$(date -I)] ${1}" >> /var/log/lock.log
# }
#
# until ! kill -0 $pid || fprintd-verify; do
#   log "Fingerprint failure"
# done
#
# log "Login success"
#
# kill $pid
