#!/bin/bash

toggle_bt_usb() {
  sudo -E virsh $1 bindows "${SCRIPTS_DIR}/assets/bt.xml"
}

toggle_bt_mod() {
  sudo $1 btusb
  sudo $1 btintel
}

toggle_bt_svc() {
  sudo systemctl $1 bluetooth.service
}

reset_host() {
  toggle_bt_svc stop
  toggle_bt_mod rmmod

  sleep 2

  toggle_bt_mod modprobe
  toggle_bt_svc start
}

reset_usb() {
  toggle_bt_usb detach-device

  sleep 2

  toggle_bt_usb attach-device
}

case "$1" in
  host) reset_host;;
  usb) reset_usb;;
esac
