# vi: ft=sh

#!/bin/zsh

alias pgc="clear && pgcli postgres postgres"
alias pm="sudo pacman"
alias pmi="yes | pm -S"
alias pmr="yes | pm -Rvns"
alias pms="pm -Ss"
alias ym="yay"
alias ymi="ym -S"
alias yms="ym -Ss"
alias sc="sudo systemctl"
alias scu="systemctl --user"
alias scs="sc start"
alias sct="sc status"
alias scou="scu stop"
alias scsu="scu start"
alias sctu="scu status"
alias scou="scu stop"
alias gacam="ga . && gcam"
alias ggpnv="ggpush --no-verify"
alias stopc='sudo docker container stop $(sudo docker container ls -lq)'
alias sshk="ssh rancher@k3s.home.dev"
alias kc="kubectl"
alias kcg="kc get"
alias kcgp="kcg pods"
alias kcga="kcg all"
alias kcgaa="kcg all --all-namespaces"
alias kcd="kc delete"
alias kcdp="kcd pod"
alias kcdj="kcd job"
alias n="nvim"
alias zs="source $XDG_CONFIG_HOME/zsh/init.zsh"
alias zc="n $XDG_CONFIG_HOME/zsh/init.zsh"
alias ze="n $XDG_CONFIG_HOME/zsh/env.zsh"
alias za="n $XDG_CONFIG_HOME/zsh/aliases.zsh"
