# vi: ft=sh

#!/bin/zsh

alias pgc="clear && pgcli postgres postgres"
alias pm="sudo pacman"
alias pmi="yes | pm -S"
alias pmr="yes | pm -Rvns"
alias pms="pm -Ss"
alias pmq="pm -Qs"
alias ym="yay"
alias ymi="ym -S"
alias yms="ym -Ss"
alias sc="sudo systemctl"
alias scu="systemctl --user"
alias scs="sc start"
alias sco="sc stop"
alias sct="sc status"
alias sce="sc enable"
alias scr="sc restart"
alias sces="sce && scs"
alias scou="scu stop"
alias scsu="scu start"
alias sctu="scu status"
alias scou="scu stop"
alias scru="scu restart"
alias sceu="scu enable"
alias gacam="ga . && gcam"
alias ggpnv="ggpush --no-verify"
alias stopc='sudo docker container stop $(sudo docker container ls -lq)'
alias kssh="ssh rancher@pi.dev.gg"
alias kc="kubectl"
alias kce="kc explain"
alias kcl="kc logs"
alias kcg="kc get"
alias kcgp="kcg pods"
alias kcga="kcg all"
alias kcgaa="kcg all --all-namespaces"
alias kcd="kc delete"
alias kcdp="kcd pod"
alias kcdj="kcd job"
alias n="nvim"
alias zs="source $XDG_CONFIG_HOME/zsh/init.zsh"
alias zc="n $XDG_CONFIG_HOME/zsh/init.zsh"
alias ze="n $XDG_CONFIG_HOME/zsh/env.zsh"
alias za="n $XDG_CONFIG_HOME/zsh/aliases.zsh"
alias ni="PYTHONPATH=/usr/lib/python2.7 npm i"
